var json_NODOSDELAPROVINCIA_2 = {
"type": "FeatureCollection",
"name": "NODOSDELAPROVINCIA_2",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Nombre": "NODO ALBERDI", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "B* Alberdi - Calle Sucre 2190", "Telef.\/Cel": "4249514", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -65.273721, -24.206722 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO LA VIÑA", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "B* Chijra - calle Mozconi 688", "Telef.\/Cel": "4263193", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -65.298812, -24.175911 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO CORONEL ARIAS", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "B* Cnel. Arias - Calle Monteagudo esquina Aguero", "Telef.\/Cel": "4249487", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -65.285026, -24.207899 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO CASTAÑEDA", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "B* 790v Castañeda - Calle Baldi esquina Solorzano", "Telef.\/Cel": "4249473", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -65.310348, -24.197207 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO SAN FRANCISCO DE ALAVA", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "TILQUIZA 781 - BARRIO SAN FRANCISCO DE ALAVA", "Telef.\/Cel": "4249478�", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -65.2807798, -24.194067 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO COPACABANA", "Tipo": "CIC", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "B* Alto Comedero - Calle Marina Vilte 590", "Telef.\/Cel": "4057031", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -65.2729987, -24.2484015 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO EVA PERON", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "B* Alto Comedero - 281 v - Calle Teniente Farias esquina Cabo Montaño", "Telef.\/Cel": "4282210", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -65.26956, -24.233709 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO 18 HECTAREAS", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "B* Alto Comedero - 6 de Marzo - Mz 17 L 6", "Telef.\/Cel": "3884054154", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -65.237926, -24.266561 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO RENE FAVAROLO - EX LA LOMA", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "B* Alto Comedero - Sector B1 MP1", "Telef.\/Cel": "4275986�", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -65.253678, -24.251721 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO SAN JOSE", "Tipo": "CIC", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS8:00 HS A 22:00HS", "Direccion": "B* San Jose", "Telef.\/Cel": "4275120", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -65.227186, -24.262663 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO CAROLINA", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "B* Carolina - Ave Hipolito Irigoyen esquina 25 de Mayo", "Telef.\/Cel": "4275910", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -65.196528, -24.25518 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO  2  (SAN JOSE)", "Tipo": "CIC", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "B* 8 de Diciembre - Calle 23 de Agosto y Valle Grande", "Telef.\/Cel": "4916994", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -65.1201358, -24.3819761 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO FATIMA", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "B* La Paz - Cuba esquina Guatemala", "Telef.\/Cel": "4916917", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -65.1113187, -24.3935809 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO PATRICIOS", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "B* Patricio - Puerto Argentino s\/n", "Telef.\/Cel": "En tramite", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -64.8588006, -24.2294302 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO LA MERCED", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "Ave Libertador esquina Mu�ecas", "Telef.\/Cel": "En tramite", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -64.8779025, -24.237335 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO NUEVA CIUDAD", "Tipo": "CIC", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "Av San Expedito esquina ave 25 de Mayo", "Telef.\/Cel": "En tramite", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -64.862404, -24.240494 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO EVA PERON", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "L2 Mz 238", "Telef.\/Cel": "3886-422072", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -64.7831724, -23.8043211 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO PURMAMARCA", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "Florida S\/N", "Telef.\/Cel": "4996020", "Modalidad": "Enfermero Medico L a V 12 hs" }, "geometry": { "type": "Point", "coordinates": [ -65.500118, -23.746121 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO SEQUEIRO", "Tipo": "HOSPITAL", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "Ecuador 53", "Telef.\/Cel": "0388 4221251", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -65.304128, -24.192857 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO DR. FERNANDO CAMPERO", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "BELGRANO 471", "Telef.\/Cel": "423270", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -64.793716, -23.814335 ] } },
{ "type": "Feature", "properties": { "Nombre": "NODO PROVIDENCIA", "Tipo": "CAPS", "Nodo": "SI", "Horario Fu": "8:00 HS A 22:00HS", "Direccion": "RINCONADA 484", "Telef.\/Cel": "En tramite", "Modalidad": "Medico y Enfermero" }, "geometry": { "type": "Point", "coordinates": [ -64.8607548, -24.2185323 ] } }
]
}
