# Generated by Django 5.2.8 on 2025-11-26 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visible', models.CharField(help_text="Ej: 'Vecino Juan', 'Padre Roberto'", max_length=50)),
                ('telefono', models.CharField(help_text='Para contacto interno, no se muestra al usuario', max_length=20)),
                ('es_verificado', models.BooleanField(default=False, help_text='Si está marcado, tú lo aprobaste manualmente')),
                ('esta_disponible', models.BooleanField(default=False, help_text='Switch ON/OFF para recibir alertas')),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario_real', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aliado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
