# Generated by Django 5.2.8 on 2025-11-26 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='aliado_emisor',
            field=models.ForeignKey(blank=True, help_text='Si el mensaje lo escribió un humano aliado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aliado'),
        ),
        migrations.CreateModel(
            name='SesionHumana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('aliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aliado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarioanonimo')),
            ],
        ),
    ]
