# Generated by Django 4.2.26 on 2025-12-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mensaje_aliado_emisor_sesionhumana'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioanonimo',
            name='zona',
            field=models.CharField(blank=True, help_text='Barrio o Localidad aproximada (Ej: Tilcara Centro, Sumay Pacha)', max_length=100, null=True),
        ),
    ]
