# Generated by Django 6.0 on 2025-12-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuarioanonimo_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioanonimo',
            name='dispositivo_modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuarioanonimo',
            name='dispositivo_os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuarioanonimo',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarioanonimo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
