# Generated by Django 6.0 on 2025-12-27 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sugerencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='core.usuarioanonimo')),
            ],
            options={
                'verbose_name_plural': 'Registros de Ubicación',
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
