# Generated by Django 6.0 on 2025-12-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_registroubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioanonimo',
            name='en_zona_roja',
            field=models.BooleanField(default=False, help_text='Indica si el usuario está en crisis activa'),
        ),
        migrations.AddField(
            model_name='usuarioanonimo',
            name='fecha_zona_roja',
            field=models.DateTimeField(blank=True, help_text='Cuándo entró en crisis', null=True),
        ),
    ]
