# Generated by Django 6.0 on 2025-12-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usuarioanonimo_en_zona_roja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('municipio', models.CharField(blank=True, max_length=200, null=True)),
                ('departamento', models.CharField(blank=True, max_length=200, null=True)),
                ('provincia', models.CharField(default='JUJUY', max_length=100)),
            ],
        ),
    ]
