# Generated by Django 6.0 on 2025-12-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ticketayuda'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroubicacion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='registroubicacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
