# Generated by Django 6.0 on 2026-01-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_registroubicacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliado',
            name='especialidad',
            field=models.CharField(choices=[('TRABAJOR_SOCIAL', 'Trabajador/a Social'), ('PSICOLOGO', 'Psicólogo/a'), ('TERAPEUTA', 'Terapeuta'), ('PSIQUIATRA', 'Psiquiatra'), ('ENFERMERO', 'Enfermero/a'), ('RELIGIOSO', 'Religioso/a'), ('VECINO', 'Vecino/a Voluntario'), ('OTRO', 'Otro (Especifique)')], default='VECINO', max_length=50),
        ),
        migrations.AddField(
            model_name='aliado',
            name='especialidad_otro',
            field=models.CharField(blank=True, help_text='Si eligió Otro', max_length=100, null=True),
        ),
    ]
